#Michael Audi - Database Extra Credit Assignment





course = {}

##course[""] = {"name":"", "cred":int(), "dept":"", "desc":""}
course["CIS 161"] = {"name":"Computer Science 1", "cred":int(4), "dept":"CIS", "desc":"Examines the nature of computer programming; includes discussion of a computer model, methods of problem solving and programming structures; information representation; algorithm construction; object-oriented design."}
course["CIS 120"] = {"name":"Computer Concepts", "cred":int(4), "dept":"CIS", "desc":"Follows the Internet and Computing Core Certificate (IC3) national standard for digital literacy used at numerous colleges and universities across the country as well as industry. Course objectives are broken down into three modules: Computer Fundamentals, Key Applications, and Living Online. Provides knowledge and skills needed to use computers successfully at the college level."}
course["MUS 118"] = {"name":"Music Technology MIDI/Audio", "cred":int(3), "dept":"MUS", "desc":"Provides hands-on instruction in current applications of music technology in a MIDI/audio studio. Use various music production tools in live sound engineering and mixing."}
course["MUS 194"] = {"name":"Big Band Jazz", "cred":int(1), "dept":"MUS", "desc":"Study and performance of music for large jazz band. One major concert is presented each term. May be repeated, no limit. Contact ensemble conductor for information about required audition."}
course["CUL 101"] = {"name":"Introduction to Culinary Arts", "cred":int(4), "dept":"CUL", "desc":"Experience the basic theory and skill sets used throughout the field of culinary arts. Topics covered include the use of hand tools and equipment found in the professional kitchen, as well as the exploration of ingredients and their functions. Students will gain a working knowledge of the fundamentals of kitchen operations, basic knife skills; an overview of stock, sauce and soup preparation; and coverage of the primary dry heat, moist heat and combination heat cooking methods. Students will also taste and evaluate products they create in class to enhance their understanding of the course material."}
course["CUL 242"] = {"name":"Charcuterie", "cred":int(4), "dept":"CUL", "desc":"Learn professional skills in variations of hors d’oeuvres and savories, seasonings, condiments, stuffed meats and curing, pickling and smoking of meat, fish and poultry. Develop proficiency in sausage-making, pâtés, terrines, galantines, and stuffed meats. Prepare a variety of charcuterie products from fresh sausage to dry cured salamis."}
course["ANTH 103"] = {"name":"Cultural Anthropology", "cred":int(4), "dept":"ANT", "desc":"Provides an introduction to the diversity of human beliefs and behaviors around the world. Explores cross-cultural similarities and differences in systems of values, family, religion, economics, politics, and social structure, including issues of race and ethnicity. The goals of this course are to foster an appreciation of cultural diversity, to use this appreciation to better understand the student's culture(s), and to learn to be active and aware participants of local and global communities."}
course["ANTH 254"] = {"name":"Magic, Witchcraft, Religion", "cred":int(4), "dept":"ANT", "desc":"Introduces students to the subject of religion in the broad anthropological context, contributes to a deeper awareness of diverse expressions of religious faith in a multicultural world, and promotes openness to and tolerance of world views different from the student's own."}
course["AUT 101"] = {"name":"Basic Electricity-Automotive", "cred":int(2), "dept":"AUT", "desc":"Provides understanding of fundamental principles of electricity. Covers basic electrical quantities, Ohm's law, power, series, and parallel circuits, magnetism, electromagnetism and an introduction to DC-current troubleshooting. Introduces student to the use of a digital multimeter and oscilloscope. Student will also be introduced to electrical schematics. A self-paced course."}
course["AUT 281"] = {"name":"Hybrid Electric Vehicles II", "cred":int(4), "dept":"AUT", "desc":"A study of HEV (hybrid electric vehicles) and EV (electric vehicles) part 2. Safety procedures will be strongly emphasized. Vehicle systems that will be covered include: Hybrid safety and service procedures, advanced hybrid batteries testing and service, advanced testing of hybrid electric motors, generators, and controls along with extensive manufacturer scan tools use and vehicle testing."}

